### ISSUE TITLE
the default iteration is 60000 in the code, but in paper it mentioned 30000?

### ISSUE THREAD

**Issue by yangqing-yq** [RunyiYang/SUNDAE#4]
the training time is around 1 hour in RTX4090. the training epochs is 60000. but in the paper is 30000. which one is correct?

**Comment by RunyiYang** [comment]
If you have a pretrained model, the iterations should be 30000. 60000 is training from scratch.

**Comment by yangqing-yq** [comment]
thanks for answering~
